name: Build

on:
  push:
  workflow_dispatch:

env:
  esp_idf_version: 'v5.2'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    strategy:
      matrix:
        esp_idf_targets: [esp32s2, esp32s3]

    outputs:
      s2_bin: ${{ steps.build.outputs.bin_path }}
      s3_bin: ${{ steps.build.outputs.bin_path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: espressif/esp-usb-bridge
          path: esp

      - name: Cache esp-idf and its tools
        id: esp-idf-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/esp/esp-idf
            ~/.espressif
            ~/build
          key: ${{ runner.os }}-esp-${{ matrix.esp_idf_targets }}-${{ env.esp_idf_version }}

      - name: Install ESP-IDF ${{ env.esp_idf_version }}
        run: |
          if [[ "${{ steps.esp-idf-cache.outputs.cache-hit }}" == "true" ]]; then
            echo "Cache hit - skipping dependency installation"
          else
            export DEBIAN_FRONTEND=noninteractive; \
            sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util; \
            sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10; \
            mkdir ~/esp; \
            cd ~/esp; \
            git clone --recursive https://github.com/espressif/esp-idf.git; \
            cd ~/esp/esp-idf; \
            ./install.sh
          fi
        shell: bash

      - name: Build for ${{ matrix.esp_idf_targets }}
        run: |
          cd esp/
          source ~/esp/esp-idf/export.sh
          idf.py set-target ${{ matrix.esp_idf_targets }}
          idf.py build
          cd build/
          esptool.py --chip ${{ matrix.esp_idf_targets }} merge_bin -o ../../esp_usb_bridge_${{ matrix.esp_idf_targets }}.bin @flash_args
          echo "::set-output name=bin_path::../../esp_usb_bridge_${{ matrix.esp_idf_targets }}.bin"
        shell: bash

      - name: Move build artifacts
        run: |
          ls -l
          # mv esp_usb_bridge_${{ matrix.esp_idf_targets }}.bin bin_files/${{ matrix.esp_idf_targets }}/

  add_and_commit:
    needs:
      - build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: add_and_commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Add latest s2 and s3 bin files'
          committer_name: Hard working robot
          default_author: github_actions
          add: '${{ needs.build.outputs.s2_bin }} ${{ needs.build.outputs.s3_bin }} --force'
          cwd: './'
