name: Build

on:
  push:
  workflow_dispatch:

env:
  esp_idf_version: 'v5.2'

jobs:
  cache_esp_idf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Cache ESP-IDF
        uses: martijnhols/actions-cache/check@v3
        id: check_cache
        with:
          path: |
            ~/esp
            ~/.espressif
          key: ESP-IDF ver-${{ env.esp_idf_version }}

      - name: Install ESP-IDF ${{ env.esp_idf_version }}
        if: steps.check_cache.outputs.cache-hit != 'true'
        run: |
          export DEBIAN_FRONTEND=noninteractive; \
          sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util; \
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10; \
          mkdir ~/esp; \
          cd ~/esp; \
          git clone --recursive https://github.com/espressif/esp-idf.git; \
          cd ~/esp/esp-idf; \
          ./install.sh
        shell: bash

  get_latest_esp_usb_bridge:
    needs:  cache_esp_idf
    runs-on: ubuntu-latest
    steps:

      - name: Cache ESP-IDF
        id: esp-idf-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/esp
            ~/.espressif
          key: ESP-IDF ver-${{ env.esp_idf_version }}
        
      - name: list  
        run: |
          ls -a -l

      - name: Checkout esp-usb-bridge repo
        uses: actions/checkout@v4
        with:
          repository: espressif/esp-usb-bridge
          path: esp

      - name: list  
        run: |
          ls -a -l

      - name: list  esp dir
        run: |
          ls -a -l esp/
